### ISSUE TITLE
Import error: undefined symbol

### ISSUE THREAD

**Issue by gravelandblood** [strawlab/python-pcl#101]
I have installed the python wrapper successfully.
But an error occurs when I import it:
```
>>> import pcl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pcl/__init__.py", line 2, in <module>
    from ._pcl import *
ImportError: /usr/local/lib/python2.7/dist-packages/pcl/_pcl.so: undefined symbol: _ZN3pcl7PCLBaseINS_8PointXYZEE13setInputCloudERKN5boost10shared_ptrIKNS_10PointCloudIS1_EEEE
```
Best Wishes!

**Comment by SinghGauravKumar** [comment]
Any solution of this?

**Comment by SkanderHannachi** [comment]
same here

**Comment by mikeroberts3000** [comment]
@SkanderHannachi these two errors don't look the same to me. One is an undefined symbol that seems to originate from python-pcl code (``_ZN3pcl7PCLBaseINS_8PointXYZEE13setInputCloudERKN5boost10shared_ptrIKNS_10PointCloudIS1_EEEE``). In contrast, https://github.com/strawlab/python-pcl/issues/79 is an undefined symbol that seems to originate from some lower-level CPython code (``PyFPE_counter``). Can you provide more detail regarding how these two issues are related?

**Comment by mikeroberts3000** [comment]
I ended up finding an astonishing workaround for this issue.

When I run ``python setup.py install``, the setup script prints out a few gcc and g++ commands (see above). If you can believe it, the workaround for this problem was to take each gcc and g++ command, copy it to the command line, and run it manually. And then to run ``python setup.py install`` again. Running the setup script again will not call gcc or g++, but will copy the relevant files to the Python site-packages folder.

So, the build environment is somehow different when invoking gcc and g++ from setup.py, as opposed to invoking gcc and g++ manually from the command line.
