### ISSUE TITLE
python 3.6 use setup.py in windows

### ISSUE THREAD

**Issue by qk1997** [strawlab/python-pcl#111]
E:\work\python-pcl-master\python-pcl-master>python setup.py
Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    if subprocess.call(['pkg-config', 'pcl_common%s' % pcl_version]) == 0:
  File "F:\Anaconda\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "F:\Anaconda\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "F:\Anaconda\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by Haofun123** [comment]
I come across the same question with you ,and I do not know how to solve it ,have you solved it?

**Comment by Sirokujira** [comment]
Download Gtk + for Windows before calling setup.py and copy the extracted binary to the pkg-config folder.

Issue #60.

**Comment by gfjiyue** [comment]
I also meet this problem. Have you solved it? I did what Sirokujira said, but it did't work.

**Comment by peterwa88** [comment]
Just want to ask where those extracted binary are located? There are too many files and directories in the GTK+(msys64) folder. Thx.

**Comment by peterwa88** [comment]
My problem is like this:

C:\~python\python-pcl-master>python setup.py install

cannot find environment PKG_CONFIG_PATH
set environment PKG_CONFIG_PATH=C:\Program Files\PCL 1.8.1\lib\pkgconfig;C:\Prog
ram Files\PCL 1.8.1\3rdParty\FLANN\lib\pkgconfig;C:\Program Files\PCL 1.8.1\3rdP
arty\Eigen\lib\pkgconfig;
F:\deep_learning\python\python-pcl-master\pkg-config\pkg-config.exe
Traceback (most recent call last):
  File "setup.py", line 153, in <module>
    if subprocess.call(['.\\pkg-config\\pkg-config.exe', 'pcl_common%s' % pcl_ve
rsion]) == 0:
  File "C:\Anaconda3\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Anaconda3\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Anaconda3\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by guishi9090** [comment]
same problem,and as i copy the extracted binary to the pkg-config folder still call that problem,

**Comment by zhangguowei0916** [comment]
me too. Have anybody solved it?  and gtk+-bundle_3.6.4-20131201_win64.zip has lost

**Comment by JohnsonQi** [comment]
> My problem is like this:
> 
> C:~python\python-pcl-master>python setup.py install
> 
> cannot find environment PKG_CONFIG_PATH
> set environment PKG_CONFIG_PATH=C:\Program Files\PCL 1.8.1\lib\pkgconfig;C:\Prog
> ram Files\PCL 1.8.1\3rdParty\FLANN\lib\pkgconfig;C:\Program Files\PCL 1.8.1\3rdP
> arty\Eigen\lib\pkgconfig;
> F:\deep_learning\python\python-pcl-master\pkg-config\pkg-config.exe
> Traceback (most recent call last):
> File "setup.py", line 153, in 
> if subprocess.call(['.\pkg-config\pkg-config.exe', 'pcl_common%s' % pcl_ve
> rsion]) == 0:
> File "C:\Anaconda3\lib\subprocess.py", line 267, in call
> with Popen(*popenargs, **kwargs) as p:
> File "C:\Anaconda3\lib\subprocess.py", line 709, in **init**
> restore_signals, start_new_session)
> File "C:\Anaconda3\lib\subprocess.py", line 997, in _execute_child
> startupinfo)
> FileNotFoundError: [WinError 2] 系统找不到指定的文件。

The same,bro
