### ISSUE TITLE
problem when importing pcl windows

### ISSUE THREAD

**Issue by skyline624** [strawlab/python-pcl#155]
Hello everyone,
I get an error message when I try to import pcl:

>>> import pcl
Traceback (most recent call last):
   File "<pyshell # 1>", line 1, in <module>
     import pcl
   File "C: \ Python35 \ lib \ site-packages \ python_pcl-0.3-py3.5-win-amd64.egg \ pcl \ __ init__.py", line 2, in <module>
     from ._pcl import *
ImportError: DLL load failed: The specified module was not found.

pcl is well in the path I do not see where it can come.
I am running windows 10 and python 3.5 pcl 1.8.1.
thank you in advance

**Comment by Qipccc** [comment]
hello
I have the same problem,win10 and python3.6 pcl1.8.1,VS2015.
did you solve it?

**Comment by niranjanreddy891** [comment]
Try with python-2.7. It worked for me. Also try installing win-7 instead of win-10

**Comment by mukhery** [comment]
I was able to use the [dependency walker](http://www.dependencywalker.com/) to open the .pyd files within the site-packages directory referenced in my error message. Doing so revealing that OpenNI2.dll was missing. I added C:\Program Files\OpenNI2\Samples\Bin, which is where OpenNI2.dll is located, to my Path environment variable and then I was able to import pcl just fine.

**Comment by lzq100123** [comment]
Same problem to me. I fixed it by installing .NET Framework 4.7.1, then I was able to import pcl (python3.5, windows7, pcl1.8.1)

**Comment by kaif15** [comment]
Had the same issue. Fixed it by starting the python interpreter in admin mode (python 3.6, windows 10, pcl 1.8.1)

**Comment by HowcanoeWang** [comment]
@mukhery thanks a lot, that does works for me!

**Comment by wedesoft** [comment]
I had to add `C:\\Program Files\OpenNI2\Redist` to the system PATH to get it to work under Windows.

**Comment by jahidmixmaster** [comment]
@wedesoft  windows 10 or what?

**Comment by wedesoft** [comment]
@jahidmixmaster Windows 7

**Comment by tjulyz** [comment]
> Had the same issue. Fixed it by starting the python interpreter in admin mode (python 3.6, windows 10, pcl 1.8.1)

Very helpful!
