### ISSUE TITLE
python setup problem (windows 10, Anaconda 3 5.0.1

### ISSUE THREAD

**Issue by ljc19800331** [strawlab/python-pcl#161]
Windows 10, Anaconda 3 (5.0.1) python setup problem.

I faced the problem and got the following error. I tried multiple methods based on the previous issues but still found the problem

C:\Users\magua\Anaconda3\python.exe C:/Users/magua/PycharmProjects/python-pcl/setup.py
Traceback (most recent call last):
set environment PKG_CONFIG_PATH=C:\Program Files\PCL 1.8.1\lib\pkgconfig;C:\Program Files\PCL 1.8.1\3rdParty\FLANN\lib\pkgconfig;C:\Program Files\PCL 1.8.1\3rdParty\Eigen\lib\pkgconfig;C:\Users\magua\PycharmProjects\python-pcl\pkg-config\pkg-config.exe;
C:\Users\magua\PycharmProjects\python-pcl\pkg-config\pkg-config.exe
  File "C:/Users/magua/PycharmProjects/python-pcl/setup.py", line 153, in <module>
    if subprocess.call(['.\\pkg-config\\pkg-config.exe', 'pcl_common%s' % pcl_version]) == 0:
  File "C:\Users\magua\Anaconda3\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\magua\Anaconda3\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\magua\Anaconda3\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

Process finished with exit code 1

**Comment by bygreencn** [comment]
Maybe, you can check https://github.com/strawlab/python-pcl/blob/master/tests/test_registration.py

**Comment by zhulf0804** [comment]
> Maybe, you can check https://github.com/strawlab/python-pcl/blob/master/tests/test_registration.py

It's good, help me too much.
Thank you.
