### ISSUE TITLE
make_statistical_outlier_filter fails for coloured point clouds

### ISSUE THREAD

**Issue by nicolas-chaulet** [strawlab/python-pcl#224]
Calling the `make_statistical_outlier_filter()` on a coloured point cloud (`PointCloud_PointXYZRGB`) fails with the following error:
```
Traceback (most recent call last):
  File "statistical_outlier_fiter.py", line 13, in <module>
    filcol =colorp.make_statistical_outlier_filter()
  File "pcl/pxi/PointCloud_PointXYZRGB_180.pxi", line 309, in pcl._pcl.PointCloud_PointXYZRGB.make_statistical_outlier_filter (pcl/_pcl_180.cpp:73606)
  File "pcl/pxi/Filters/StatisticalOutlierRemovalFilter_180.pxi", line 135, in pcl._pcl.StatisticalOutlierRemovalFilter_PointXYZRGB.__cinit__ (pcl/_pcl_180.cpp:25536)
TypeError: __cinit__() takes exactly 1 positional argument (0 given)
```
Code to replicate:
```
import pcl
colorp = pcl.PointCloud_PointXYZRGB()
filcol =colorp.make_statistical_outlier_filter()
```

**Comment by niranjanreddy891** [comment]
@nicolas-chaulet, have you tried using `RGBA ` instead of `RGB`.

**Comment by josauder** [comment]
How would I go about this issue when I have XYZI Point Clouds?
