### ISSUE TITLE
Using PointCloudColorHandleringRGBField returns errors

### ISSUE THREAD

**Issue by CQUlds** [strawlab/python-pcl#227]
I wanted to display the color data in my viewer,  but returned an error when adding a color point cloud. This my code and error:

import pcl.pcl_visualization as pclv
import pcl

ptcloud_rgb = pcl.load_XYZRGB('E:/python test/point cloud/all_test.pcd')

visual = pclv.PCLVisualizering('3D viewer')
visual.SetBackgroundColor(0, 0, 0)

pccolor = pclv.PointCloudColorHandleringRGBField(ptcloud_rgb)
visual.AddPointCloud(ptcloud_rgb, pccolor, b'pt')

flag = True
while flag:
    flag != visual.WasStopped()
    visual.SpinOnce()
    # pcl_sleep (0.01)
    # pass

Traceback (most recent call last):
__cinit__
  File "E:/python test/point cloud/pcshow.py", line 21, in <module>
    visual.AddPointCloud(ptcloud_rgb, pccolor, b'pt')
  File "pcl\pxi\Visualization\PCLVisualizering.pxi", line 120, in pcl.pcl_visualization.PCLVisualizering.AddPointCloud (pcl\pcl_visualization.cpp:10011)
TypeError: an integer is required
__dealloc__

someone who can help me to this issue?

**Comment by niranjanreddy891** [comment]
@CQUlds, try using `RGBA` instead of `RGB`

**Comment by soulslicer** [comment]
Did you manage to solve this?
