### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by larsmans** [strawlab/python-pcl#28]
I get the following test failures on Ubuntu w/ PCL 1.6, NumPy 1.7.1, Python 2.7.5. Tests run with `nosetests tests/` after doing `make clean all` in the source directory.

```
======================================================================
FAIL: testSegment (test.TestSegmentCylinder)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/larsb/src/patty/python-pcl/tests/test.py", line 157, in testSegment
    self.assertEqual(len(indices), SEGCYLIN)
AssertionError: 11462 != 11461

======================================================================
FAIL: testFilterNeg (test.TestSegmenterNormal)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/larsb/src/patty/python-pcl/tests/test.py", line 242, in testFilterNeg
    self._tneg(c)
  File "/home/larsb/src/patty/python-pcl/tests/test.py", line 224, in _tneg
    self.assertEqual(c.size, 1013)
AssertionError: 1015 != 1013

======================================================================
FAIL: testFilterPos (test.TestSegmenterNormal)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/larsb/src/patty/python-pcl/tests/test.py", line 234, in testFilterPos
    self._tpos(c)
  File "/home/larsb/src/patty/python-pcl/tests/test.py", line 218, in _tpos
    self.assertEqual(c.size, 22747)
AssertionError: 22745 != 22747

======================================================================
FAIL: testFilterPosNeg (test.TestSegmenterNormal)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/larsb/src/patty/python-pcl/tests/test.py", line 249, in testFilterPosNeg
    self._tpos(c)
  File "/home/larsb/src/patty/python-pcl/tests/test.py", line 218, in _tpos
    self.assertEqual(c.size, 22747)
AssertionError: 22745 != 22747
```

Finally, after reporting the number of failures, `nosetests` segfaults. Any idea what this could be?

**Comment by aminm2a** [comment]
I have a test fail, do somebody know the problem ?

======================================================================
ERROR: testResize (__main__.TestExceptions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 246, in testResize
    self.assertRaises(MemoryError, self.p.resize, -1)
  File "C:\Anaconda\lib\unittest\case.py", line 473, in assertRaises
    callableObj(*args, **kwargs)
  File "pcl\_pcl.pyx", line 249, in pcl._pcl.PointCloud.resize (pcl\_pcl.cpp:5281)
RuntimeError: vector<T> too long

======================================================================
FAIL: testSegment (__main__.TestSegmentCylinder)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 179, in testSegment
    self.assertEqual(len(indices), SEGCYLIN)
AssertionError: 11448 != 11462

----------------------------------------------------------------------
Ran 25 tests in 7.635s

FAILED (failures=1, errors=1)
