### ISSUE TITLE
Error while installing python module 

### ISSUE THREAD

**Issue by scizors** [strawlab/python-pcl#280]
I cannot able to instal python modules  

I am using windows 10 
Case2. use 1.8.1
PCL all in one 1.9.1 
python version 3.5

issue

(pyrhon3.5) C:\Users\rsr5le\Desktop\python-pcl-master>python setup.py build_ext -i
cannot find environment PKG_CONFIG_PATH
set environment PKG_CONFIG_PATH=C:\Program Files\PCL 1.8.1\lib\pkgconfig;C:\Program Files\PCL 1.8.1\3rdParty\FLANN\lib\pkgconfig;C:\Program Files\PCL 1.8.1\3rdParty\Eigen\lib\pkgconfig;
C:\Users\rsr5le\Desktop\python-pcl-master\pkg-config\pkg-config.exe
Traceback (most recent call last):
  File "setup.py", line 152, in <module>
    if subprocess.call(['.\\pkg-config\\pkg-config.exe', 'pcl_common%s' % pcl_version]) == 0:
  File "C:\Users\rsr5le\.conda\envs\pyrhon3.5\lib\subprocess.py", line 247, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\rsr5le\.conda\envs\pyrhon3.5\lib\subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "C:\Users\rsr5le\.conda\envs\pyrhon3.5\lib\subprocess.py", line 957, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

(pyrhon3.5) C:\Users\rsr5le\Desktop\python-pcl-master>

**Comment by scizors** [comment]
Anyone set this Environment variable before  instal python modules
PCL_ROOT

set PCL_ROOT=$(PCL Install FolderPath)

PATH

(pcl 1.8.1) set PATH=$(PCL_ROOT)/bin/;$(OPEN_NI2_ROOT)/Tools;$(VTK_ROOT)/bin;%PATH%

**Comment by scizors** [comment]
ya i did it
