### ISSUE TITLE
pcl1.9.1 & python-pcl

### ISSUE THREAD

**Issue by coldcoda** [strawlab/python-pcl#318]
Hello,
I have installed PCL1.9.1,can I install python-pcl in my computer?

Windows10
python3.7 & python2.7
PCL1.9.1

**Comment by themightyoarfish** [comment]
Apparently, no. Compiling with 1.9.1 (after minor fixes to the setup.py), one is met with this error:

```
>>> import pcl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rasmus/Downloads/python-pcl-0.2.0/pcl/__init__.py", line 2, in <module>
    from ._pcl import *
ImportError: dlopen(/Users/rasmus/Downloads/python-pcl-0.2.0/pcl/_pcl.cpython-37m-darwin.so, 2): Symbol not found: __ZN5boost6system15system_categoryEv
```

**Comment by themightyoarfish** [comment]
In my case, the problem was fixed by recompiling PCL. I had some issues with my boost installation, so probably recompiling against the currently installed boost libraries fixed this issue.

**Comment by moonstarsky37** [comment]
For coldcoda's question
I tested PCL 1.9.0 with Win10, python 3.6 with conda is okey.
The results about a simple viewer (table_scene_lms400.pcd) is following
https://i.imgur.com/tVXkxJ8.png
I think 1.9.1 not change a lot.
