### ISSUE TITLE
I can find python-pcl by "pip list",but cannot import pcl

### ISSUE THREAD

**Issue by djlbet123** [strawlab/python-pcl#359]
My environment:
Ubuntu 18.04
anaconda 3.7
python 3.7

Here my pcl version looked by pip list:  
 python-pcl                         0.3.0a1  

but when I go into python and import pcl
It said that

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/summerriver/.local/lib/python3.7/site-packages/pcl/__init__.py", line 2, in <module>
    from ._pcl import *
ImportError: libpcl_keypoints.so.1.7: cannot open shared object file: No such file or directory

I have spent lots of time in it,but still can't fix it.Help me! Thanks~

**Comment by iscsrl** [comment]
From this answer https://askubuntu.com/a/1170661/1003856

```
sudo add-apt-repository ppa:sweptlaser/python3-pcl
sudo apt update
sudo apt install python3-pcl

```
After you've done that then you should be able to run:

`python3 -c 'import pcl'`

**Comment by FabianSchuetze** [comment]
When I try your suggestions @iscsrl  , I receive the following error: 

```python
ModuleNotFoundError: No module named 'pcl._pcl'
```
Does somebody have an idea how I can solve this?

**Comment by sreshu** [comment]
@iscsrl 's way works fine for python 3.6.9
