### ISSUE TITLE
missing PKG_CONFIG_PATH in windows 10

### ISSUE THREAD

**Issue by KatharinaSchmidt** [strawlab/python-pcl#370]
## My Environment
* Operating System and version: Windows 10 version 1909 with python 3.4.4 & 3.6.0
* Compiler: VS 2017
* PCL Version: 1.9.1
* Cython Version: 0.29.21

## Context
I tried to use `python setup.py build_ext -i` to install the python module

## Current Behavior
I got the error following error message 

D:\Masterarbeit\NN\python-pcl>python setup.py build_ext -i
cannot find environment PKG_CONFIG_PATH
set environment PKG_CONFIG_PATH=C:\Program Files\PCL 1.9.1\lib\pkgconfig;C:\Program Files\PCL 1.9.1\3rdParty\FLANN\lib\pkgconfig;C:\Program Files\PCL 1.9.1\3rdParty\Eigen\lib\pkgconfig;
D:\Masterarbeit\NN\python-pcl\pkg-config\pkg-config.exe
Traceback (most recent call last):
  File "setup.py", line 159, in <module>
    if subprocess.call(['.\\pkg-config\\pkg-config.exe', 'pcl_common%s' % pcl_version]) == 0:
  File "C:\Users\katha\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\katha\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Users\katha\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

I hope you can help me to fix this.

**Comment by sineadkearney** [comment]
I had the same error. I created these two environment variables which fixed the error:

PKG_CONFIG_PATH = C:\Program Files\PCL 1.9.1\lib\pkgconfig;C:\Program Files\PCL 1.9.1\3rdParty\FLANN\lib\pkgconfig;C:\Program Files\PCL 1.9.1\3rdParty\Eigen\lib\pkgconfig;

PCL_VERSION = 1.9
