### ISSUE TITLE
python-pcl not working with python 3.6.x in Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by ArghyaChatterjee** [strawlab/python-pcl#399]
## My Environment
* Operating System and version: Ubuntu 18.04 LTS
* Compiler: python 3.6.9
* PCL Version: 1.8.x
* Cython Version: 0.29.16

When I tried to install python-pcl with pip3:
```
pip3 install python-pcl
```
It downloads the wheel file `python_pcl-0.3.0a1-cp36-cp36m-manylinux1_x86_64.whl`. After installing, when I tried to import:
```
arghya@arghya-Erazer-X7849-MD60379:~$ python3
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pcl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/arghya/.local/lib/python3.6/site-packages/pcl/__init__.py", line 2, in <module>
    from ._pcl import *
ImportError: libpcl_keypoints.so.1.7: cannot open shared object file: No such file or directory
```
N.B: I can use python-pcl with python 2.7 with same configuration in my pc using `sudo apt-get install libpcl-dev -y` command but can't work with python 3.6.x and my project requires python version 3.

**Comment by Marina-Banov** [comment]
you can try with `pip install python3-pcl`

**Comment by DanielTakeshi** [comment]
Unfortunately it seems like many of us are getting this issue. See https://github.com/strawlab/python-pcl/issues/317

**Comment by 459737087** [comment]
> Unfortunately it seems like many of us are getting this issue. See #317

Hi, this is a bad circle, you  add this link,and that link involves this link.

**Comment by 459737087** [comment]
and I can't run it in python3.X

**Comment by BeBeBerr** [comment]
> and I can't run it in python3.X

It should work with python3.6. See https://github.com/strawlab/python-pcl/issues/374 . You need to manually copy the package folder though.

**Comment by pk1996** [comment]
Try this. 
https://github.com/strawlab/python-pcl/pull/371
