### ISSUE TITLE
ImportError: libDummyDevice.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by wd15** [strawlab/python-pcl#70]
When importing the pcl Python library the following happens

     >>> import pcl
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/dwheeler/anaconda/lib/python2.7/site-packages/pcl/__init__.py", line 2, in <module>
        from ._pcl import * 
    ImportError: libDummyDevice.so.0: cannot open shared object file: No such file or directory

The OS is Ubuntu 14.04. PCL was installed using the instructions in http://pointclouds.org/downloads/linux.html. pcl-python was installed from f17c686b63fe.

**Comment by wd15** [comment]
Follow up comment: setting

    $ export LD_LIBRARY_PATH=/usr/lib/OpenNI2/Drivers/

allows the `import pcl` to work.

**Comment by tesparrow** [comment]
I have the same problem, but the above does not work

ldd _pcl.so  gives the libDummyDevice.so.0 is found, after running 

export LD_LIBRARY_PATH=/usr/lib/OpenNI2/Drivers/ 

but within with python I still get 

ImportError: libDummyDevice.so.0: cannot open shared object file: No such file or directory.

Any ideas why?

**Comment by tesparrow** [comment]
Follow up comment, 

after rebooting dd _pcl.so gives the libDummyDevice.so.0  as not found.

**Comment by zahidmak** [comment]
Hi strawlab,

Any update on this issue. I am using Ubuntu 14.04. And I am seeing below error. Not sure what could the reason.

from ._pcl import *
ImportError: libDummyDevice.so.0: cannot open shared object file: No such file or directory

I am stuck on this for last 3 days. Any help is appreciated.

Thank you,

**Comment by OmarMAmin** [comment]
when i run ldd _pcl.so 

i got 
`/usr/local/lib/python2.7/dist-packages/pcl$ ldd /usr/local/lib/python2.7/dist-packages/pcl/_pcl.so | grep libpcl
	libpcl_io.so.1.7 => not found
	libpcl_segmentation.so.1.7 => not found
	libpcl_features.so.1.7 => not found
	libpcl_filters.so.1.7 => not found
	libpcl_surface.so.1.7 => not found
	libpcl_search.so.1.7 => not found
	libpcl_kdtree.so.1.7 => not found
	libpcl_octree.so.1.7 => not found
	libpcl_common.so.1.7 => not found
`
though all these libraries are located in usr/local/lib
does any one know how to fix that ?

Thank you

**Comment by ding-hai** [comment]
I got the same error,can anyone help mme
