### ISSUE TITLE
Build errors on Ubuntu 14.04

### ISSUE THREAD

**Issue by allanis79** [strawlab/python-pcl#93]
Hello,

I am using Ubuntu 14.04
Python 2.7.6
Cython version 0.20.1post0

I am trying to install python binding for PCL, but when ever i am running the command : python setup.py install , i am getting the following error:

> Package openni-dev was not found in the pkg-config search path.
Perhaps you should add the directory containing `openni-dev.pc'
to the PKG_CONFIG_PATH environment variable
Package 'openni-dev', required by 'pcl_io', not found
Package openni-dev was not found in the pkg-config search path.
Perhaps you should add the directory containing `openni-dev.pc'
to the PKG_CONFIG_PATH environment variable
Package 'openni-dev', required by 'pcl_io', not found
Package openni-dev was not found in the pkg-config search path.
Perhaps you should add the directory containing `openni-dev.pc'
to the PKG_CONFIG_PATH environment variable
Package 'openni-dev', required by 'pcl_io', not found
Package openni-dev was not found in the pkg-config search path.
Perhaps you should add the directory containing `openni-dev.pc'
to the PKG_CONFIG_PATH environment variable
Package 'openni-dev', required by 'pcl_io', not found
running install
running build
running build_py
running build_ext
skipping 'pcl/_pcl.cpp' Cython extension (up-to-date)
building 'pcl._pcl' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DEIGEN_YES_I_KNOW_SPARSE_MODULE_IS_NOT_STABLE_YET=1 -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c pcl/_pcl.cpp -o build/temp.linux-x86_64-2.7/pcl/_pcl.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
In file included from pcl/_pcl.cpp:358:0:
pcl/shared_ptr_assign.h:1:29: fatal error: pcl/point_cloud.h: No such file or directory
 #include <pcl/point_cloud.h>
                             ^
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 

I tried to debug the error, but i was not able to install it.

Can anyone help me with the issue?

Thanks.

**Comment by criminalking** [comment]
Same error T_T

**Comment by criminalking** [comment]
I have solved this problem now !!!
You should change "openni-dev" to "libopenni" in all **pcl_io-1.7.pc** files.

**Comment by OmarMAmin** [comment]
@criminalking 
i did what you said, but i had a different problem 

`>>> import pcl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pcl/__init__.py", line 2, in <module>
    from ._pcl import *
ImportError: libpcl_io.so.1.7: cannot open shared object file: No such file or directory
`

i tried to run ldd to the _pcl.so located in python dist-packages and got 
`/usr/local/lib/python2.7/dist-packages/pcl$ ldd /usr/local/lib/python2.7/dist-packages/pcl/_pcl.so | grep libpcl
	libpcl_io.so.1.7 => not found
	libpcl_segmentation.so.1.7 => not found
	libpcl_features.so.1.7 => not found
	libpcl_filters.so.1.7 => not found
	libpcl_surface.so.1.7 => not found
	libpcl_search.so.1.7 => not found
	libpcl_kdtree.so.1.7 => not found
	libpcl_octree.so.1.7 => not found
	libpcl_common.so.1.7 => not found
`

can u please let me know how to fix this ?

**Comment by bowen03** [comment]
To build or install python-pcl need to install openni2 first, I followed the [http://blog.csdn.net/lymemoryzz/article/details/51274095](url) and [http://blog.csdn.net/lymemoryzz/article/details/51274095](url) to install the OpenNI-Linux-x64-2.2 , finally I can import pcl in pycharm IDE .

**Comment by hiram94** [comment]
This may work: https://github.com/strawlab/python-pcl/issues/97

**Comment by ljc19800331** [comment]
@bowen03 Hello bowen, would it possible if you show me the process of installing the python-pcl? I tried many times based on the tutorial but failed to install in linux. Even I can installed once, I can only import pcl but failed import other module such as registration or visualization. Thanks.
