### ISSUE TITLE
Windows environment setup

### ISSUE THREAD

**Issue by uiossha** [strawlab/python-pcl#96]
My environment:
PCL 1.7.2 all-in-one installed
OPENNI2 installed
Cython installed using anaconda2

Run: python setup.py install 
failed:

Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    if subprocess.call(['pkg-config', 'pcl_common%s' % pcl_version]) == 0:
  File "C:\Anaconda2\lib\subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Anaconda2\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "C:\Anaconda2\lib\subprocess.py", line 959, in _execute_child
    startupinfo)
WindowsError: [Error 2]

**Comment by jckchow** [comment]
Running into the same problem on my machine
PCL 1.8 all-in-one-installer
Cython installed using anaconda

Still haven't found the solution.

**Comment by Gegaktakan** [comment]
I had the same issue as well.
Cython, PCL 1.6 and openNI installed

I didn't use anaconda though, so my errors read the same a uiossha except "C:\Python27\lib\subprocess.py" instead of "C:\Anaconda2\lib\subprocess.py". I'm not 100% sure what not using anaconda would do differently if anything, but we seem to be having the same issue with and without it so probably not too much..

**Comment by NatholBMX** [comment]
Did this get a solution yet? I'm running into the same errors as you guys.

**Comment by Sirokujira** [comment]
Download Gtk + for Windows before calling setup.py and copy the extracted binary to the pkg-config folder.

Issue #60.

**Comment by peterwa88** [comment]
Just want to ask where those extracted binary are located? There are too many files and directories in the GTK+(msys64) folder. Thx.

**Comment by peterwa88** [comment]
My problem is like this:

C:~python\python-pcl-master>python setup.py install

cannot find environment PKG_CONFIG_PATH
set environment PKG_CONFIG_PATH=C:\Program Files\PCL 1.8.1\lib\pkgconfig;C:\Prog
ram Files\PCL 1.8.1\3rdParty\FLANN\lib\pkgconfig;C:\Program Files\PCL 1.8.1\3rdP
arty\Eigen\lib\pkgconfig;
F:\deep_learning\python\python-pcl-master\pkg-config\pkg-config.exe
Traceback (most recent call last):
File "setup.py", line 153, in
if subprocess.call(['.\pkg-config\pkg-config.exe', 'pcl_common%s' % pcl_ve
rsion]) == 0:
File "C:\Anaconda3\lib\subprocess.py", line 267, in call
with Popen(*popenargs, **kwargs) as p:
File "C:\Anaconda3\lib\subprocess.py", line 709, in init
restore_signals, start_new_session)
File "C:\Anaconda3\lib\subprocess.py", line 997, in _execute_child
startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by JohnsonQi** [comment]
> My problem is like this:
> 
> C:~python\python-pcl-master>python setup.py install
> 
> cannot find environment PKG_CONFIG_PATH
> set environment PKG_CONFIG_PATH=C:\Program Files\PCL 1.8.1\lib\pkgconfig;C:\Prog
> ram Files\PCL 1.8.1\3rdParty\FLANN\lib\pkgconfig;C:\Program Files\PCL 1.8.1\3rdP
> arty\Eigen\lib\pkgconfig;
> F:\deep_learning\python\python-pcl-master\pkg-config\pkg-config.exe
> Traceback (most recent call last):
> File "setup.py", line 153, in
> if subprocess.call(['.\pkg-config\pkg-config.exe', 'pcl_common%s' % pcl_ve
> rsion]) == 0:
> File "C:\Anaconda3\lib\subprocess.py", line 267, in call
> with Popen(*popenargs, **kwargs) as p:
> File "C:\Anaconda3\lib\subprocess.py", line 709, in init
> restore_signals, start_new_session)
> File "C:\Anaconda3\lib\subprocess.py", line 997, in _execute_child
> startupinfo)
> FileNotFoundError: [WinError 2] 系统找不到指定的文件。

Have you solved this problem?
